include: package:lints/recommended.yaml


analyzer:
  language:
    strict-raw-types: true

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
