// AUTO GENERATED BY NATIVE_DOC_DARTIFIER. DO NOT EDIT!
// Regenerate this file by running tool/prepare_dartify_test.dart

import 'package:jni/jni.dart';
import '../bindings.dart';

bool useEnums() {
  final example = Example();
  final isTrueUsage =
      example.enumValueToString(Example$Operation.ADD) ==
      'Addition'.toJString();
  return isTrueUsage;
}
