// AUTO GENERATED BY NATIVE_DOC_DARTIFIER. DO NOT EDIT!
// Regenerate this file by running tool/prepare_dartify_test.dart

import 'package:jni/jni.dart';
import '../bindings.dart';

bool backAndForthStrings() {
  const name = 'World';
  final example = Example();
  final greeting = example.greet(name.toJString())?.toDartString();
  print(greeting);
  return greeting == 'Hello World';
}
